apiVersion: v1
kind: Service
metadata:
  name: dog-breed-detector
  labels:
    app: dog-breed-detector
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: dog-breed-detector
